apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: total-access-role-binding
  namespace: hackmeeting-salon-rk
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: total-access-role
subjects:
- kind: ServiceAccount
  name: hackmeeting-sa
  namespace: hackmeeting-salon-rk
